### ISSUE TITLE
how to use chrome logger

### ISSUE THREAD

**Issue by bonaca** [ccampbell/chromelogger#72]
- so I installed chrome extension - chrome logger
-  download and include 'ChromePhp.php'; in my page
- write: ChromePhp::log('Hello console!'); - nothing happpend, console is empty !
- also tried: console.log('sea'); - no success

What is wrong or missing ?

**Comment by mindplay-dk** [comment]
It's also not working for me anymore. Something changed in Chrome maybe?

**Comment by mindplay-dk** [comment]
Oddly, the version number shown in Chrome web store is 4.1.1 and dated December 10, 2016.

The latest tagged version is 4.1.0 dated September 24, 2014 - and the next commit was in 2017, so it's hard to say where this 4.1.1 version came from.

@ccampbell any idea?

**Comment by ccampbell** [comment]
Hmm I checked recently and it was working. I'll have another look today. As for the version I made some changes that I pushed up to the chrome web store version that I forgot to commit back to GitHub. I updated the GitHub version with them last week tho so it should be up to date. 

I haven't pushed the current github version to the chrome web store yet. It was using an out of date API so that could be the issue.

**Comment by ccampbell** [comment]
I just committed a fix. Hopefully this should fix the issue. I will upload the new version to the Chrome Web Store in a few mins.

@bonaca did you also make sure to “activate” the host for the domain you want to see the logs on? If the extension is ready to log the icon will be blue:

<img width="38" alt="screen shot 2017-09-29 at 10 47 40 am" src="https://user-images.githubusercontent.com/259316/31021388-b16b6ae6-a503-11e7-9bca-35394c796e11.png">

**Comment by mindplay-dk** [comment]
@ccampbell yep, working again! thanks! :-)

**Comment by boan-jfm** [comment]
It still doesn't work for me, I have the Chromelogger version 4.1.2, and Chrome version 61.0.3163.100 (Officiel version) (64-bit) :-(

The icone is blue, and I am getting a "X-ChromeLogger-Data" header in the response, but it's not showing up in the console, all log levels are enabled.

**Comment by mindplay-dk** [comment]
@boan2010 it looks like our chrome-logger payload is somehow corrupted! I'm looking into it.
